### ISSUE TITLE
Visualise Painted Point Cloud

### ISSUE THREAD

**Issue by afonso-sousa** [Song-Jingyu/PointPainting#1]
Hi. Thanks for sharing your work. I am struggling to visualise the painted point cloud. Can you share the code you used to get the projected point cloud images for the Framework Overview?

Thank you in advance.

**Comment by Song-Jingyu** [comment]
Hi,

Thanks for your interest. For visualizing the painted pointcloud, I was also working on that as I am writing the project report. I might share a script to visualize the pointcloud and let you know when I finished that!

Best,
Jingyu

**Comment by Song-Jingyu** [comment]
@AfonsoSalgadoSousa 
Hi! Thanks for your interest in our repo. You can now follow https://github.com/Song-Jingyu/PointPainting#running-inference to see how to run a demo.

Best,
Jingyu
