### ISSUE TITLE
Question about model architecture

### ISSUE THREAD

**Issue by darrenjkt** [Song-Jingyu/PointPainting#12]
Hi Song-Jingyu,

Thanks for your work with point painting. Just got a question about the model architecture in regards to adding more lidar input features. 

Did you have to modify the model architecture to be able to accommodate more input features? 

I have looked through the code and configs but didn't seem to find any modifications. However, I'm not too clear how the model can be fed with additional [input channels (s0,s1,s2,s3)](https://github.com/Song-Jingyu/PointPainting/blob/35c7d9acfa9d18fd8071caf824a1bd8ab9603018/detector/tools/cfgs/dataset_configs/painted_kitti_dataset.yaml#L49) and learn to take advantage of those features without modifying the layer shapes, loss function, or some sort.

Could you help me clarify this? Also, what are s0,s1,s2,s3? Do these form a one-hot vector of class labels of the classes "0: background, 1: bicycle, 2: car, 3: person"?

**Comment by Song-Jingyu** [comment]
Hi! 
I got very busy these days and cannot give you clear links to code we changed and why.

There is some dataset file and config file that we modified to achieve this function. I would recommend comparing the original OpenPCDet with ours so you may get a sense of how to change the code to fit the input.

**Comment by darrenjkt** [comment]
ok no problem. Thanks for your reply.
