### ISSUE TITLE
the command about demo and test

### ISSUE THREAD

**Issue by Frank-DA** [Song-Jingyu/PointPainting#13]
请问在运行demo的命令中，--ext .npy是什么？可以提供一下你成功的命令的例子吗？
I want to know what is "--ext .npy" when I run the demo.py ?Can you offer a successfull command example? 
并且，你的readme里只写了如何开始训练，没有写如何测试。测试的命令是和openpcdet相同的吗？
Moreover,  eadme only writes how to start training, not how to test. Is the test command the same as openpcdet?

**Comment by Song-Jingyu** [comment]
Thanks for your questions!

For your first question, --ext .npy means the pointcloud file has the npy format.

For the second question, you can definitely test it using the openpcdet provided command. What I use as the results is the training log which records evaluation results.

**Comment by Frank-DA** [comment]
感谢回复。Thank you for your reply. 
但是我仍然对这个参数有疑问。But， I still have questions about this parameter.
我在接触您的代码之前单独可视化Openpcdet的时候并没有运用这个参数。
I visualized openpcdet separately before  your code. This parameter was not used at that time. 
这是我可视化openpcdet的命令。The following is my command before:
python demo.py --cfg_file ../output/kitti_models/pointpillar/default/pointpillar.yaml 
--ckpt../output/kitti_models/pointpillar/default/ckpt/checkpoint_epoch_80.pth 
--data_path ../data/kitti/testing/velodyne/000008.bin 
---------------------------------------------------------------------------------------------------------------------------
训练好这个代码之后，我没有在输出文件夹找到后缀是.npy的文件。
After training your code, I didn't find a file with the "XXX .npy" in the output folder.
所以，您可以更具体地说明这个参数吗？或者不介意的话提供一下您的可视化命令。
So, can you specify this parameter more specifically? If you don't mind, provide your visualization command。

**Comment by Song-Jingyu** [comment]
This is because we use the painted pointcloud which we stored using .npy format.

**Comment by chrisyan** [comment]
> 

Hi Jingyu, Thank you very much for your work. Can I understand it this way: Currently this algorithm is not able to inference directly with the raw LiDAR data, i.e. it can only use the painted point cloud as input. 
If this is the case, how can I inference directly on the raw LiDAR data? Thanks a lot!
