### ISSUE TITLE
I want to know validation MAP's recall point number.

### ISSUE THREAD

**Issue by 87Donghyung** [Song-Jingyu/PointPainting#14]
Hello, I read your paper. I think your idea is really interesting. I just want to know if the BEV mAP values in below table in your paper are based on recall 40 or recall11. Thank you.

![table1](https://user-images.githubusercontent.com/92224708/140879276-1129649b-0639-4273-af04-06626dcbcf1f.png)

**Comment by Song-Jingyu** [comment]
I am not the author of this paper actually. This is just an unofficial implementation of PointPainting.
