### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by 18303848764** [Song-Jingyu/PointPainting#17]
hello ! thank you so much! when i run python.py ,there are some error,so i want to ask you for help. 
INFO - 2021-12-17 16:03:24,257 - database_sampler - Database filter by difficulty Pedestrian: 2168 => 2075
2021-12-17 16:03:24,258   INFO  Database filter by difficulty Cyclist: 704 => 581
INFO - 2021-12-17 16:03:24,258 - database_sampler - Database filter by difficulty Cyclist: 704 => 581
2021-12-17 16:03:24,264   INFO  Loading KITTI dataset
INFO - 2021-12-17 16:03:24,264 - painted_kitti_dataset - Loading KITTI dataset
2021-12-17 16:03:24,399   INFO  Total samples for KITTI dataset: 3712
INFO - 2021-12-17 16:03:24,399 - painted_kitti_dataset - Total samples for KITTI dataset: 3712
段错误 (核心已转储)
  this is the problem.
good luck!

**Comment by Song-Jingyu** [comment]
I am really unsure about your help. But I would recommend checking your dataset and see whether it is complete.
