### ISSUE TITLE
Painted point clouds having artifacts

### ISSUE THREAD

**Issue by kshitij3112** [Song-Jingyu/PointPainting#18]
Thank you for providing the code and your efforts. I have tried to replicate the results but when I run painting.py, I get a point cloud that does not seem correct. As you can see in the image below, the whole left part should not be there. Do you have any idea about it?
Thanks in advance :
![painted_pointcloud](https://user-images.githubusercontent.com/30115649/149509733-9dad5954-98d0-41a5-996f-2e76fdb9f51f.png)
)

**Comment by Song-Jingyu** [comment]
Hi,

Sorry for the late reply. I am not sure about this issue as I did not check all the frames. Is this problem consistent in every frame?

**Comment by kshitij3112** [comment]
Hello,

Yes, it was consistent. The problem is that in painting.py, the script is not filtering the objects which lie behind the camera. So we get both the front and back points.

To solve this:
`true_where_front = lidar_raw[:,0] > 0 `
has to be added after line https://github.com/Song-Jingyu/PointPainting/blob/main/painting/painting.py#L184

and then Line 185 and 200 should be modified as:
`true_where_point_on_img_r = true_where_x_on_img_r & true_where_y_on_img_r & true_where_front`
`true_where_point_on_img_l = true_where_x_on_img_l & true_where_y_on_img_l & true_where_front`
