### ISSUE TITLE
How to use other lidar detection frameworks such as Voxel-RCNN etc?

### ISSUE THREAD

**Issue by Hiram9270** [Song-Jingyu/PointPainting#19]
hello， @Song-Jingyu ，Your work is great. I am now thinking about how to use your Point Painting framework on other lidar detection frameworks, such as Voxel-RCNN on OpenPCDet or some frameworks that are not integrated in OpenPCDet.
Looking forward to your answer.
Thank you very much.

**Comment by Bonener** [comment]
hello, @Song-Jingyu , what does the "Remember you have to specify the --ext parameter" means, can you give a example about this step ?

**Comment by Song-Jingyu** [comment]
> hello， @Song-Jingyu ，Your work is great. I am now thinking about how to use your Point Painting framework on other lidar detection frameworks, such as Voxel-RCNN on OpenPCDet or some frameworks that are not integrated in OpenPCDet. Looking forward to your answer. Thank you very much.

I did not have a plan to extend this to other detectors but you are totally welcome to use the this repo as reference and extend it!

**Comment by Song-Jingyu** [comment]
> 

Hi, you can do this like --ext .npy
