### ISSUE TITLE
Warning: NaN or Inf found in input tensor

### ISSUE THREAD

**Issue by wayne1627** [Song-Jingyu/PointPainting#20]
i tried to add 3 more rgb color attributions, but it turns out
` Warning: NaN or Inf found in input tensor`
what can i do about this?
hoping for your reply

**Comment by wayne1627** [comment]
@Song-Jingyu 
Hi, when i tried to train SECONDNet with your painted_lidar,
it tells me
`Warning: NaN or Inf found in input tensor`

i changed `DATA_CONFIG: 
    _BASE_CONFIG_: cfgs/dataset_configs/painted_kitti_dataset.yaml`
in second.yaml
and then run the command`python train.py --cfg_file cfgs/kitti_models/second_painted.yaml --batch_size 1`
to trained the model.
why it goes wrong like this?`Warning: NaN or Inf found in input tensor`
is there something i missed?

**Comment by Song-Jingyu** [comment]
Sorry for the late reply. Try to check if you have correctly loaded the input data.
