### ISSUE TITLE
Memory leak in demo pipeline

### ISSUE THREAD

**Issue by ChaoticEar** [Song-Jingyu/PointPainting#22]
I tried demo.py to seem how my painted detector model works and task was killed by system at about 180th instance.
![001](https://user-images.githubusercontent.com/38167416/174215091-ce1a2ffe-4d91-4d57-a05e-e801468f8d84.png)
![0](https://user-images.githubusercontent.com/38167416/174215126-579256fd-35a6-4ddf-a016-be27d776affb.png)
![3](https://user-images.githubusercontent.com/38167416/174215158-687ecc93-37ff-459b-9995-9f529285dbbd.png)

I checked GPU status and GPU memory keeps going up which eventually caused OOM and process was killed by system. Any ideas that might work this out will be grateful.

**Comment by Song-Jingyu** [comment]
Hi,

demo.py was provided by OpenPCDet. And I didn't use demo.py for Pointpainting. It is recommended to check issues in OpenPCDet repo!
