### ISSUE TITLE
demo.py QLibraryPrivate::unload succeeded

### ISSUE THREAD

**Issue by G-hx** [Song-Jingyu/PointPainting#24]
Hello, I have completed some training and testing of pointpillars_painted through train.py and evel.py, but the following problems cannot be solved when running demo.py, I hope to get your reply, thank you.
![2022-07-11 20-49-50 的屏幕截图](https://user-images.githubusercontent.com/78303303/178269024-487f7144-2b33-47b5-8062-19a2aaa45ad1.png)

**Comment by Song-Jingyu** [comment]
It looks like some visualization dependencies (like QT) issue. Can you try to search that issue online or on QT5 git to see if others have same issue?
