### ISSUE TITLE
demo.py   point cloud in the visualization is not colored

### ISSUE THREAD

**Issue by G-hx** [Song-Jingyu/PointPainting#25]
When running demo.py, the point cloud in the visualization is not colored. Is this a normal horse? My visualization-related files use the source code in the Openpcet project and have not been modified. Do I need to modify the following visualization-related code? I hope you can give me some advice. Thank you very much, sorry for your inconvenience.
![2022-07-11 21-55-58 的屏幕截图](https://user-images.githubusercontent.com/78303303/178281501-1e0f9b2e-07ca-4cd6-9b7d-5276caf3ed38.png)

**Comment by Song-Jingyu** [comment]
We modify some visualization_util script. Can you take a look at the read me inference section?
