### ISSUE TITLE
What is the FPS of the whole framework？

### ISSUE THREAD

**Issue by EliomEssaim** [Song-Jingyu/PointPainting#27]
I try to run the whole framework in ROS. The FPS of my node is about 1.6 and the most time consuming is PointPainting. The part of pointpainting cost about 0.5 seconds(deeplabv3plus).
But I'm not sure the performance is the normal result or just something wrong with my code.
Could you tell me what's the FPS of the whole framework？

**Comment by Song-Jingyu** [comment]
I think that's a reasonable time cost. Runtime is not our main focus so we didn't measure it.

**Comment by Yuepengxin** [comment]
> I try to run the whole framework in ROS. The FPS of my node is about 1.6 and the most time consuming is PointPainting. The part of pointpainting cost about 0.5 seconds(deeplabv3plus). But I'm not sure the performance is the normal result or just something wrong with my code. Could you tell me what's the FPS of the whole framework？

Hello! I would like to ask, have you already encapsulated pointpainting into ROS? How did you do it? Can you provide a detailed introduction?Can you  share your work with me?
Thank you in advance.

**Comment by EliomEssaim** [comment]
> 

ROS is just a mean of communication. It's easy to use pointpainting in ROS. For some reason, I can't share my work with you. You can start by running an ros node to publish camera and lidar messages. The ros node is then initialized in the pointpainting project to process these messages.

**Comment by Yuepengxin** [comment]
> > 
> 
> ROS is just a mean of communication. It's easy to use pointpainting in ROS. For some reason, I can't share my work with you. You can start by running an ros node to publish camera and lidar messages. The ros node is then initialized in the pointpainting project to process these messages.

Thank you for your reply. Actually, I have already encapsulated pointpillars into ROS, which is my work process:
https://blog.csdn.net/weixin_58207716/article/details/129472906
May I ask if it is possible to follow this approach to point painting work?Do I need to pay attention to any issues during the process of encapsulating ROS with pointpainting?
