### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by Yuepengxin** [Song-Jingyu/PointPainting#29]
Hello, thanks for your excellent work.I recently tried to run your work in the environment of ubuntu18.04 and python3.7.The previous work has been completed, but I encountered difficulties in the final visualization step.
After I installed 'mayavi' according to your prompt, I executed the visualization command 'python demo.py --cfg_file cfgs/kitti_models/pointpillar_painted.yaml --ckpt /home/ypx/ws/PointPainting_ws/detector/output/kitti_models/pointpillar_painted After /default/ckpt/checkpoint_epoch_80.pth --data_path /home/ypx/ws/PointPainting_ws/detector/data/kitti/training/painted_lidar/000000.npy --ext .npy', an error 'ImportError: Could not import appeared backend for traitsui. Make sure you have a suitable UI toolkit like PyQt/PySide or wxPython installed.’.
I tried to solve it, replaced various versions of 'mayavi, pyqt5, vtk, PySide', but still had the same error.So I would like to know what version of the visualization software you use? And what are its dependencies?Can you give me some guidance?Looking forward to your reply.

**Comment by Yuepengxin** [comment]
![screenshot_64](https://user-images.githubusercontent.com/103159809/204790629-ce40f2d2-ac66-43a4-8f92-f4cdaa081c7e.png)
![screenshot_65](https://user-images.githubusercontent.com/103159809/204790648-40d481d3-b4d9-46a0-bea5-936ece2d88c1.png)
![screenshot_66](https://user-images.githubusercontent.com/103159809/204790671-9dfbeb6a-1b66-46ed-a2af-30bc89c687ca.png)

**Comment by Yuepengxin** [comment]
Hello! I have been exploring this visualization problem for some time. However, no solution has been found. I have installed mayavi, vtk, pyqt5 and other dependencies, 
![screenshot_64](https://user-images.githubusercontent.com/103159809/204790949-a636746b-965c-4ea4-a4fb-b3b98f7c4181.png)
![screenshot_65](https://user-images.githubusercontent.com/103159809/204790975-53ad8ac4-0bff-4090-8c06-9e3ee22de03b.png)

but an error is reported:
![screenshot_66](https://user-images.githubusercontent.com/103159809/204791003-503119d7-587d-44b6-a760-0d641befc186.png)

So, I want to ask your opinion on this question, and what version of mayavi do you use? What version of python is used in your environment? This question is important to me，can you help me? Thank you very much,sorry for your inconvenience.

**Comment by Song-Jingyu** [comment]
Hi,

I can't remember since it is really a while ago and I don't have the laptop I used for this project with me now. This seems to be an issue with mayavi on your system, can you make sure you can run mayavi first? Maybe try some demo tests from online tutorials.

**Comment by Yuepengxin** [comment]
> Hi,
> 
> I can't remember since it is really a while ago and I don't have the laptop I used for this project with me now. This seems to be an issue with mayavi on your system, can you make sure you can run mayavi first? Maybe try some demo tests from online tutorials.



Thank you very much for your reply.
After various attempts, I come to the same conclusion as you: Mayavi may be the problem. But I have installed mayavi and its various dependencies in the virtual environment. As evidenced by the screenshot in the previous question.But visualization still failed.I have reproduced another point cloud 3D object detection algorithm based on openpcdet framework. At that time, the author left two visual interfaces for selection, one mayavi and the other open3d. I was successful in using open3d to realize visualization, but mayavi was unsuccessful.
I have made many attempts and searched a lot of information about the mayavi visualization of your project, but it is still unsuccessful. So, I want to ask you how to operate your visualization? How did you successfully deploy mayavi for visualization? Which version is used? What dependencies are used? How can I implement your rendering?
![图片](https://user-images.githubusercontent.com/103159809/206351205-04805a98-e126-4e76-8141-444c3d9d2085.png)
I know your computer is not around now, but can you help solve this problem when it is convenient for you? It bothered me for a long time. Thank you. Thanks again for your reply.

**Comment by Soodep** [comment]
> > Hi,
> > I can't remember since it is really a while ago and I don't have the laptop I used for this project with me now. This seems to be an issue with mayavi on your system, can you make sure you can run mayavi first? Maybe try some demo tests from online tutorials.
> 
> Thank you very much for your reply. After various attempts, I come to the same conclusion as you: Mayavi may be the problem. But I have installed mayavi and its various dependencies in the virtual environment. As evidenced by the screenshot in the previous question.But visualization still failed.I have reproduced another point cloud 3D object detection algorithm based on openpcdet framework. At that time, the author left two visual interfaces for selection, one mayavi and the other open3d. I was successful in using open3d to realize visualization, but mayavi was unsuccessful. I have made many attempts and searched a lot of information about the mayavi visualization of your project, but it is still unsuccessful. So, I want to ask you how to operate your visualization? How did you successfully deploy mayavi for visualization? Which version is used? What dependencies are used? How can I implement your rendering? ![图片](https://user-images.githubusercontent.com/103159809/206351205-04805a98-e126-4e76-8141-444c3d9d2085.png) I know your computer is not around now, but can you help solve this problem when it is convenient for you? It bothered me for a long time. Thank you. Thanks again for your reply.

I am facing the same issue, did you solve it?

**Comment by Song-Jingyu** [comment]
Hey all the process I did to visualize is mentioned in Readme. I would definitely recommend using a machine that you know for sure you have Mayavi works correctly.
