### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by 861482002** [Song-Jingyu/PointPainting#32]
RuntimeError: Error compiling objects for extension

**Comment by Song-Jingyu** [comment]
Hi I can help if you can provide more information.

**Comment by zhiranyan** [comment]
Hi, i have the same error when i execute "python setup.py develop"
From my point of view, it could be caused by cuda and pytorch version compatibility. What is your cuda, pytorch etc. version? many thanks!

> Hi I can help if you can provide more information.
