### ISSUE TITLE
when i run setup.py develop there are some questions

### ISSUE THREAD

**Issue by 861482002** [Song-Jingyu/PointPainting#33]
LINK : fatal error LNK1181: 无法打开输入文件“D:\A_github\PointPainting-main\detector\build\temp.win-amd64-3.8\Release\pcdet\ops\iou3d_nms\src\iou3d_cpu.obj”
error: command 'D:\\A-Visual Studio-c++\\Professional\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

**Comment by Song-Jingyu** [comment]
Hi it looks you are on Windows? I haven't tested this repo there and I would recommend using Linux (Ubuntu) for this repo.
