### ISSUE TITLE
ImportError: cannot import name 'VoxelGenerator' from 'spconv.utils

### ISSUE THREAD

**Issue by Soodep** [Song-Jingyu/PointPainting#34]
python -m pcdet.datasets.kitti.painted_kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/painted_kitti_dataset.yaml
gives me the following error:

 in transform_points_to_voxels
    from spconv.utils import VoxelGenerator
ImportError: cannot import name 'VoxelGenerator' from 'spconv.utils' (/home/UNT/sd0570/anaconda3/envs/pointpainting/lib/python3.8/site-packages/spconv/utils/_init_.py)

I am getting this import error. Is it because of the mismatch in spconv version? I just wanted to know which version of spconv you are using because openpcdet has special requirements. Could you please specify the version of  following:
1. CUDA
2. Pytorch
3. spconv
4. cudatoolkit

**Comment by Soodep** [comment]
This was because I was using spconv2.x, but for this project we have to strictly use spconv1.2.1. Once i installed the spconv1.2.1, this problem was solved.

**Comment by Song-Jingyu** [comment]
Thanks for leaving your notes here!
