### ISSUE TITLE
Painted point cloud not visible

### ISSUE THREAD

**Issue by Soodep** [Song-Jingyu/PointPainting#35]
I trained my model and when i run the demo I get this result :
![image](https://user-images.githubusercontent.com/9031472/220139164-2847a21d-c7f8-4497-94fe-c259240b667d.png)
If it is to go by this approach, I should have got the painted point cloud in this image, but I dont think the point cloud are painted here. I used one of the .npy files from training/painted_lidar folder. Is there anything wrong I am doing here. Your suggestion would be greatly appreciated.

**Comment by Song-Jingyu** [comment]
Hi,

I think you should be able to visualize the painted pointcloud following https://github.com/Song-Jingyu/PointPainting#running-inference.

**Comment by Soodep** [comment]
I followed the same method but I am getting unpainted lidar point cloud in final detection. Shouldn't the final detection show the painted lidar point cloud.

**Comment by Zifei68** [comment]
> I followed the same method but I am getting unpainted lidar point cloud in final detection. Shouldn't the final detection show the painted lidar point cloud.

Hallo, do you find the way to visiualize it in the end? Because I've gotton the same problem like you. When I try to use both the ros and this way for visiualization, there're no painted parts. Looking forwrd to your valuable answer, thanks 🙏
