### ISSUE TITLE
关于复现结果：

### ISSUE THREAD

**Issue by Karkers** [Song-Jingyu/PointPainting#37]
我在自己的机器上复现了Pointpainting，但是最终的结果无法达到原文的效果，尤其是行人类别，Mod。仅有46.0145，请问这是什么情况。
I reproduced Pointpainting on my own machine, but the final result cannot reach the original, especially for the pedestrian category, the Mod is only 46.0145.

**Comment by Song-Jingyu** [comment]
Hi, please refer to our results in readme.
