### ISSUE TITLE
How to generate the semantic segmentation images?

### ISSUE THREAD

**Issue by ZhangYu1ing** [Song-Jingyu/PointPainting#5]
Hi, 

may I ask how do you get the semantic segmentation images that are shown in the 'Results & Discussion' subsection?
Thanks in advance.
![image](https://user-images.githubusercontent.com/37301722/119979176-deef9e80-bfba-11eb-99d8-6611a3cedfa2.png)

**Comment by Song-Jingyu** [comment]
Hi,

I am not in charge of this part. But I think you can show the raw image and the mask (containing the segmentation class that we care i.e., vehicle, pedestrian and cyclist) together.

Best,
Jingyu Song
