### ISSUE TITLE
Some questions about 

### ISSUE THREAD

**Issue by LCJHust** [Song-Jingyu/PointPainting#6]
Hi,
    Thank you for your excellent work! I tried to reproduce the results in the source paper with your code,  but failed（with default configture）. Have you reproduce the similarity performance on kitti val dataset with the paper's, please?

**Comment by Song-Jingyu** [comment]
No. I did not get the same results in the paper. The main reason may be the amount of train set we use (specified by OpenPCDet) is different from that in the paper. You are welcome to try to dig into that part.

**Comment by LCJHust** [comment]
> No. I did not get the same results in the paper. The main reason may be the amount of train set we use (specified by OpenPCDet) is different from that in the paper. You are welcome to try to dig into that part.

Thank you for your reply. And another question, if the segmentation weights trained from Mapillary/cityscapes/kitti dataset as the same as the paper mentioned?

**Comment by Song-Jingyu** [comment]
You may check mmsegmentation repo for details. I can confirm the weight we use for DeepLabV3+ is trained on cityscapes!
