### ISSUE TITLE
Which KItte datasets do I need to download?

### ISSUE THREAD

**Issue by HITjian** [Song-Jingyu/PointPainting#7]
Hello, thanks for your excellent work,
Could you tell me which which KItte dataset do I need to download?
there are :
Download left color images of object data set (12 GB)
Download right color images, if you want to use stereo information (12 GB)
Download the 3 temporally preceding frames (left color) (36 GB)
Download the 3 temporally preceding frames (right color) (36 GB)
Download Velodyne point clouds, if you want to use laser information (29 GB)
Download camera calibration matrices of object data set (16 MB)
Download training labels of object data set (5 MB)
......
and so on.
Please tell me, I am looking for your reply!

**Comment by yswi** [comment]
If you click the link on the website, you can see the name of the zip file. For instance, if you click 'Download left color images of the object data set (12 GB)', you can see that the corresponding zip file is named ""data_object_image_2.zip"". The zip file corresponds to "image_2"  indicated in our readme.
![image](https://user-images.githubusercontent.com/55126407/126733603-649e16b5-f0c3-4c5f-a5ef-caabe71c79fb.png)
![image](https://user-images.githubusercontent.com/55126407/126733624-0f94d74f-651a-46d7-853e-8c99d8b9f79a.png)

**Comment by HITjian** [comment]
Thank you very much for your detailed answer! I have got it.
