### ISSUE TITLE
how to calculate mAP?

### ISSUE THREAD

**Issue by Shaoqing26** [Song-Jingyu/PointPainting#8]
Hi,
      I wonder to know that how to calculate the mAP which describes in the pointpainting paper. It seems that didn't explain what it is in the paper. Can u provide the mAP code? or tell us how to calculate it.

**Comment by Song-Jingyu** [comment]
Sorry for the late reply. I was not on the original working desktop so I cannot find the exact direction for the output result. But you should not manually calculate the mAP, instead you can search a folder with keyword like output and there is a text file inside it. The text file should have all you want!
