### ISSUE TITLE
how to solve the Importerror when run "python painting.py"

### ISSUE THREAD

**Issue by Frank-DA** [Song-Jingyu/PointPainting#9]
A problem was encountered while running the command"python painting.py". Does anyone have a solution？
“ImportError:libtorch_cpu.so:cannot open shared object file:No such file or directory.”
After checking the tracback , It seems to be because of mmcv, but mmcv has been installed with the documentation.

**Comment by Song-Jingyu** [comment]
I haven't encountered this problem. But I think you should be able to solve by using a GPU-integrated computer. Maybe the cpu version of Pytorch is not compatible with the mmcv.
